## Hypergraph Product Code example

Hypergraph product (HGP) code is a family of CSS codes whose stabilizer generator matrix is obtained from a hypergraph product of two classical linear codes.

The construction of the $[[n,k,d]]$ CSS code is based on two binary linear seed codes, $\mathcal{C}_i$ for $i \in \{1,2\}$, each with parameters $[n_i,k_i,d_i]$. These are defined as the kernel of an $r_i \times n_i$ check matrix $H_i$, where each matrix has a rank of $n_i - k_i$. The hypergraph product yields two classical codes $\mathcal{C}_{X,Z}$ with parity-check matrices:
\begin{equation}
H_x = [H_1 \otimes I_{n_2},  I_{r_1} \otimes H_2^T] 
\end{equation}

\begin{equation}
H_z = [I_{n_1} \otimes H_2,  H_1^T \otimes I_{r_2}],
\end{equation}

where $I_m$ is the $m$-dimensional identity matrix. These two codes then yield a hypergraph product code via the CSS construction.

Here we will create a HGP code based on two Steane codes, so both parity check matrices are the same ($H_1 = H_2$):


In [1]:
import numpy as np
from quick.dataset.common import Steane
from quick.core.code.qldpc.hgp import HGP

# Get the parity check matrix H_i (i \in \{1,2\})
H1 = Steane().H
H2 = Steane().H
print("The parity check matrix for the Steane code (Hi) is:")
print(H1)


The parity check matrix for the Steane code (Hi) is:
[[0 0 0 0 0 0 0 0 0 0 1 1 1 1]
 [0 0 0 0 0 0 0 0 1 1 0 0 1 1]
 [0 0 0 0 0 0 0 1 0 1 0 1 0 1]
 [0 0 0 1 1 1 1 0 0 0 0 0 0 0]
 [0 1 1 0 0 1 1 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0 0 0 0 0 0 0]]


Next, we will build the HGP code and check its parity check matrices. Also, I'll present some properties of HGP codes:

In [2]:
hgp_code = HGP(H1, H2)
hx = hgp_code.Hx
hz = hgp_code.Hz
print(f"The shape of X parity check matrix is {np.shape(hx)} and the shape of Z matrix is {np.shape(hz)}.")
print(f"The number of logical qubits is {hgp_code.num_logical} and the distance of it is {hgp_code.distance}.")

The shape of X parity check matrix is (84, 232) and the shape of Z matrix is (84, 232).
The number of logical qubits is 64 and the distance of it is 3.
