## Lifted product code
The lifted product code is an generalization of hypergraph product. For more information, please refer to https://arxiv.org/abs/2012.04068.

### protograph 
In general lifted product is defined on a ring, but here we only consider it on the extension of $GF(2)$ field that is implemented in our platform. 

An $l \times l$ circulant matrix A over $\mathbb{F}_2$ take the form 
\begin{equation*}
A = 
\begin{pmatrix}
a_0 & a_{l-1} & \cdots a_1 \\
a_1 & a_{0} & \cdots a_2 \\
\cdots \\
a_{l-1} & a_{l-2} & \cdots a_2 \\
\end{pmatrix} = a_0I + a_1P + \cdots + a_{l-1}P^{l-1}
\end{equation*}

where $I$ is the $l \times l$ identity matrix and is the $l \times l$ permutation matrix representing the right cyclic shift by one position. Since $P^l= I$, we see that the ring of all $l \times l$ circulant matrices over $\mathbb{F}_2$ is isomorphic to the ring $R_l = \mathbb{F}_2[x]/(x^l- 1) = GF(2^l)$ of polynomials over $\mathbb{F}_2$ modulo the polynomial $x^l- 1$. Hence the circulant matrix A can be uniquely represented by the polynomial:
\begin{equation*}
    p_a = a_0 + a_1x + \cdots + a_{l-1}x^{l-1}.
\end{equation*}
The $GF(2^l)$ is the extended field of $GF(2)$, and element $a$ is the polynomial representation on $GF(2^l)$. We can either represente $a$ as the binary vector $(a_{l-1}, a_{l-2}, \cdots, a_0)$ or the integer given by transforming the vector to decimal. 

If we construt a matrix over the ring 
\begin{equation*}
M =  
\begin{pmatrix}
p_a & p_b & \cdots \\
\vdots & \cdots &p_n
\end{pmatrix} 
\end{equation*}
the matrix $M$ is called __protograph__.

In [1]:
import numpy as np
from quick.core.code.protograph import Protograph

base_matrix = np.array([[0,11,7, 12],[1,8,1,8],[11,0,4,8],[6,2,4,12]])
base_matrix = np.exp2(base_matrix).astype(int)
proto = Protograph(base_matrix)
print('Protograph:')
print(proto.galois_matrix)

Protograph:
[[   1 2048  128 4096]
 [   2  256    2  256]
 [2048    1   16  256]
 [  64    4   16 4096]]


### Lift
__Lift__ is implemented by substituting the each elements in $M$ by the corresponding circulant matrix
\begin{equation*}
L(M) =  \begin{pmatrix}
a_0I + a_1P + \cdots + a_{l-1}P^{l-1}  & b_0I + b_1P + \cdots + b_{l-1}P^{l-1} & \cdots \\
\vdots & \cdots & n_0I + n_1P + \cdots + n_{l-1}P^{l-1}
\end{pmatrix} 
\end{equation*}

In [2]:
from quick.core.code.cldpc.classical import to_classical
lift = to_classical(graph = proto, galois_order = 3)
print('Lift:')
lift.num_physical, lift.num_logical

Lift:


(12, 5)

$L(M)$ is a parity check matrix for classical quasi-cyclic code.

### lifted product
For two protographs $M_1, M_2$, the lifted product is done by first performing hypergraph-product like operation to the protographs
\begin{equation*}
M_x = [M_1\otimes I_{n_2}, \; I_{r_1} \otimes M_2^T], \; M_z = [I_{n_1} \otimes M_2, \; M_1^T \otimes I_{r_2}]
\end{equation*}
where $M_x, M_z$ are also protographs. The second steps is to lift $M_x, M_z$ to give the parity check matrixs
\begin{equation*}
    H_x = L(M_x), \; H_z = L(M_z).
\end{equation*}
$H_x, H_z$ is a CSS code. 

In [3]:
from quick.core.code.qldpc.lp import LP
LP = LP(proto,proto, 13)
print('Lifted product code:')
LP.num_physical, LP.num_logical

Lifted product code:


(416, 18)